function Strings = buildPhreeqcStrings(model, states, t, phaseData, mineralData)
%BUILDPHREEQCSTRINGS Build PHREEQC input strings for all cells at step t.
%
% Inputs:
%   model       - MRST model
%   states      - state cell array
%   t           - current time step index
%   phaseData   - struct from computePhaseMassesAndPressures
%   mineralData - struct from computeMineralogy
%
% Output:
%   Strings     - cell array (nc x 1), each entry is a full PHREEQC input
%                 string for cell i (empty for inactive cells)

    G  = model.G;
    nc = G.cells.num;

    %% Kinetic data (same as in your original code)
    % Methanogenesis
    mu_MET   = model.Kinetic.mu_MET;
    b_MET    = model.Kinetic.b_MET;
    Y_MET    = model.Kinetic.Y_MET;
    K_Dmet   = model.Kinetic.K_Dmet;
    K_Amet   = model.Kinetic.K_Amet;
    MW_MET   = model.Kinetic.MW_MET;
    m_MET    = model.Kinetic.m_MET;
    M0_MET   = model.Kinetic.M0_MET;     %#ok<NASGU>
    Nmax_MET = model.Kinetic.Nmax_MET;
    Mmax_MET = model.Kinetic.Mmax_MET;
    Mmin_MET = model.Kinetic.Mmin_MET;

    % Sulfate reduction
    mu_SRB   = model.Kinetic.mu_SRB;
    b_SRB    = model.Kinetic.b_SRB;
    Y_SRB    = model.Kinetic.Y_SRB;
    K_Dsrb   = model.Kinetic.K_Dsrb;
    K_Asrb   = model.Kinetic.K_Asrb;
    MW_SRB   = model.Kinetic.MW_SRB;
    m_SRB    = model.Kinetic.m_SRB;
    M0_SRB   = model.Kinetic.M0_SRB;     %#ok<NASGU>
    Nmax_SRB = model.Kinetic.Nmax_SRB;
    Mmax_SRB = model.Kinetic.Mmax_SRB;
    Mmin_SRB = model.Kinetic.Mmin_SRB;

    % Acetogenesis
    mu_ACE   = model.Kinetic.mu_ACE;
    b_ACE    = model.Kinetic.b_ACE;
    Y_ACE    = model.Kinetic.Y_ACE;
    K_Dace   = model.Kinetic.K_Dace;
    K_Aace   = model.Kinetic.K_Aace;
    MW_ACE   = model.Kinetic.MW_ACE;
    m_ACE    = model.Kinetic.m_ACE;
    M0_ACE   = model.Kinetic.M0_ACE;     %#ok<NASGU>
    Nmax_ACE = model.Kinetic.Nmax_ACE;
    Mmax_ACE = model.Kinetic.Mmax_ACE;
    Mmin_ACE = model.Kinetic.Mmin_ACE;

    % Iron reduction
    mu_FRB   = model.Kinetic.mu_FRB;
    b_FRB    = model.Kinetic.b_FRB;
    Y_FRB    = model.Kinetic.Y_FRB;
    K_Dfrb   = model.Kinetic.K_Dfrb;
    K_Afrb   = model.Kinetic.K_Afrb;     %#ok<NASGU>
    MW_FRB   = model.Kinetic.MW_FRB;
    m_FRB    = model.Kinetic.m_FRB;
    M0_FRB   = model.Kinetic.M0_FRB;     %#ok<NASGU>
    Nmax_FRB = model.Kinetic.Nmax_FRB;
    Mmax_FRB = model.Kinetic.Mmax_FRB;
    Mmin_FRB = model.Kinetic.Mmin_FRB;

    %% Phase / solution data (from phaseData, mineralData)
    Sw                 = phaseData.Sw;
    Sg                 = phaseData.Sg;
    pH                 = phaseData.pH;
    Units              = phaseData.Units;

    K                  = phaseData.K;
    Na                 = phaseData.Na;
    Mg                 = phaseData.Mg;
    Ca                 = phaseData.Ca;
    Cl                 = phaseData.Cl;
    C4                 = phaseData.C4;
    S6                 = phaseData.S6;
    S2                 = phaseData.S2;
    Fe3                = phaseData.Fe3;
    Fe2                = phaseData.Fe2;
    Si                 = phaseData.Si;
    Acetate            = phaseData.Acetate;

    SRB_Biomass        = phaseData.SRB_Biomass;
    MET_Biomass        = phaseData.MET_Biomass;
    ACE_Biomass        = phaseData.ACE_Biomass;
    FRB_Biomass        = phaseData.FRB_Biomass;

    mass_H2O_Profile   = phaseData.mass_H2O_Profile;
    mol_H2_Profile     = phaseData.mol_H2_Profile;
    mol_CO2_Profile    = phaseData.mol_CO2_Profile;
    mol_CH4_Profile    = phaseData.mol_CH4_Profile;
    mol_H2S_Profile    = phaseData.mol_H2S_Profile;
    mol_N2_Profile     = phaseData.mol_N2_Profile;

    pH2                = phaseData.pH2;
    pCO2               = phaseData.pCO2;
    pCH4               = phaseData.pCH4;
    pH2S               = phaseData.pH2S;
    pN2                = phaseData.pN2;

    Vg                 = phaseData.Vg;
    pressure_atm       = phaseData.pressure_atm;
    temp               = phaseData.temp;
    tot_time           = phaseData.tot_time;
    steps              = phaseData.steps;

    % Minerals (initial moles per cell)
    Calcite_i          = mineralData.Calcite_i;
    Dolomite_i         = mineralData.Dolomite_i;
    Quartz_i           = mineralData.Quartz_i;
    Anhydrite_i        = mineralData.Anhydrite_i;
    Goethite_i         = mineralData.Goethite_i;
    Brucite_i          = mineralData.Brucite_i;
    Portlandite_i      = mineralData.Portlandite_i;
    Pyrite_i           = mineralData.Pyrite_i;
    Gypsum_i           = mineralData.Gypsum_i;

    %% Build strings per cell
    Strings = cell(nc,1);

    for i = 1:nc

        if (Sg(i) ~= 0 || Sw(i) >= 1e-3)

            IPCstringCell = { ...
                'KNOBS', ...
                '-iterations 800', ...
                '-step_size 30', ...
                '-convergence_tolerance 1e-10', ...
                'RATES', ...
                'MET', ...
                '-start', ...
                ['20 rate = ', num2str(mu_MET), '/86400/', num2str(Y_MET), ...
                    '*kin("Biomass_MET")*mol("H2")/(', num2str(K_Dmet), ...
                    '+mol("H2"))*tot("Carbonate(4)")/(', num2str(K_Amet), ...
                    '+tot("Carbonate(4)"))'], ...
                '30 if (TC<45) then rate = -rate * (TC-10)*(TC+10-2*45)/(45-10)^2', ...
                '40 if (TC>=45) then rate = -rate * (TC-122)*(TC+122-2*45)/(45-122)^2', ...
                '50 if (-LA("H+")<7.7) then rate = -rate * (-LA("H+")-4.1)*(-LA("H+")+4.1-2*7.7)/(7.7-4.1)^2', ...
                '60 if (-LA("H+")>=7.7) then rate = -rate * (-LA("H+")-10.2)*(-LA("H+")+10.2-2*7.7)/(7.7-10.2)^2', ...
                '70 if (-LA("H+")>=10.2) then rate = 0', ...
                '80 if (-LA("H+")<=4.1) then rate = 0', ...
                '90 if (TC<=10) then rate = 0', ...
                '100 if (TC>=122) then rate = 0', ...
                '101 TDS = (RHO - TOT("water")/SOLN_VOL)*1e3', ...
                '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2', ...
                '103 if (TDS>300) then rate = 0', ...
                '110 put(rate,1) ', ...
                '120 moles = rate* TIME', ...
                '200 SAVE moles', ...
                '-end', ...
                'SRB', ...
                '-start', ...
                ['20 rate = ', num2str(mu_SRB), '/86400/', num2str(Y_SRB), ...
                    '*kin("Biomass_SRB")*mol("H2")/(', num2str(K_Dsrb), ...
                    '+mol("H2"))*mol("SulfateO4-2")/(', num2str(K_Asrb), ...
                    '+mol("SulfateO4-2"))'], ...
                '30 if (TC<48) then rate = -rate * (TC-10)*(TC+10-2*48)/(48-10)^2', ...
                '40 if (TC>=48) then rate = -rate * (TC-113)*(TC+113-2*48)/(48-113)^2', ...
                '50 if (-LA("H+")<7.01) then rate = -rate * (-LA("H+")-1)*(-LA("H+")+1-2*7.01)/(7.01-1)^2', ...
                '60 if (-LA("H+")>=7.01) then rate = -rate * (-LA("H+")-11.5)*(-LA("H+")+11.5-2*7.01)/(7.01-11.5)^2', ...
                '70 if (-LA("H+")>=11.5) then rate = 0', ...
                '80 if (-LA("H+")<=1) then rate = 0', ...
                '90 if (TC<=10) then rate = 0', ...
                '100 if (TC>=113) then rate = 0', ...
                '101 TDS = (RHO - TOT("water")/SOLN_VOL)*1e3', ...
                '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2', ...
                '103 if (TDS>300) then rate = 0', ...
                '110 put(rate,2) ', ...
                '120 moles = rate* TIME', ...
                '200 SAVE moles', ...
                '-end', ...
                'ACE', ...
                '-start', ...
                ['20 rate = ', num2str(mu_ACE), '/86400/', num2str(Y_ACE), ...
                    '*kin("Biomass_ACE")*mol("H2")/(', num2str(K_Dace), ...
                    '+mol("H2"))*tot("Carbonate(4)")/(', num2str(K_Aace), ...
                    '+tot("Carbonate(4)"))'], ...
                '30 if (TC<38) then rate = -rate * (TC-25)*(TC+25-2*38)/(38-25)^2', ...
                '40 if (TC>=38) then rate = -rate * (TC-72)*(TC+72-2*38)/(38-72)^2', ...
                '50 if (-LA("H+")<7.04) then rate = -rate * (-LA("H+")-3.6)*(-LA("H+")+3.6-2*7.04)/(7.04-3.6)^2', ...
                '60 if (-LA("H+")>=7.04) then rate = -rate * (-LA("H+")-9.5)*(-LA("H+")+9.5-2*7.04)/(7.04-9.5)^2', ...
                '70 if (-LA("H+")>=9.5) then rate = 0', ...
                '80 if (-LA("H+")<=3.6) then rate = 0', ...
                '90 if (TC<=25) then rate = 0', ...
                '100 if (TC>=72) then rate = 0', ...
                '101 TDS = (RHO - TOT("water")/SOLN_VOL)*1e3', ...
                '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2', ...
                '103 if (TDS>300) then rate = 0', ...
                '110 put(rate,3) ', ...
                '120 moles = rate* TIME', ...
                '200 SAVE moles', ...
                '-end', ...
                'FRB', ...
                '-start', ...
                ['20 rate = ', num2str(mu_FRB), '/86400/', num2str(Y_FRB), ...
                    '*kin("Biomass_FRB")*mol("H2")/(', num2str(K_Dfrb), ...
                    '+mol("H2"))'], ...
                '30 if (TC<30) then rate = -rate * (TC-10)*(TC+10-2*30)/(30-10)^2', ...
                '40 if (TC>=30) then rate = -rate * (TC-100)*(TC+100-2*30)/(30-100)^2', ...
                '50 if (-LA("H+")<7) then rate = -rate * (-LA("H+")-1)*(-LA("H+")+1-2*7)/(7-1)^2', ...
                '60 if (-LA("H+")>=7) then rate = -rate * (-LA("H+")-10)*(-LA("H+")+10-2*7.)/(7-10)^2', ...
                '50 if (-LA("H+")>=10) then rate = 0', ...
                '60 if (-LA("H+")<=1) then rate = 0', ...
                '70 if (TC<=10) then rate = 0', ...
                '80 if (TC>=100) then rate = 0', ...
                '90 if (EQUI("Goethite")<1e-8) then rate = 0', ... % fixed "the" -> "then"
                '80 put(rate,4) ', ...
                '90 moles = rate* TIME', ...
                '200 SAVE moles', ...
                '-end', ...
                'Biomass_MET', ...
                '-start', ...
                '20 rate = get(1)', ...
                ['30 Y = ', num2str(Y_MET)], ...
                ['40 b = ', num2str(b_MET/86400)], ...
                '50 rate = Y*rate-b*M', ...
                '60 moles = -rate * TIME', ...
                ['70 N = (M-moles)*', num2str(MW_MET*1/m_MET)], ...
                ['80 if (M-moles)<', num2str(Mmin_MET), ' then moles = M-', num2str(Mmin_MET)], ...
                ['90 if (N>=', num2str(Nmax_MET), ') then moles = M-', num2str(Mmax_MET)], ...
                '200 Save moles', ...
                '-end', ...
                'Biomass_SRB', ...
                '-start', ...
                '20 rate = get(2)', ...
                ['30 Y = ', num2str(Y_SRB)], ...
                ['40 b = ', num2str(b_SRB/86400)], ...
                '50 rate = Y*rate-b*M', ...
                '60 moles = -rate * TIME', ...
                ['70 N = (M-moles)*', num2str(MW_SRB*1/m_SRB)], ...
                ['80 if (M-moles)<', num2str(Mmin_SRB), ' then moles = M-', num2str(Mmin_SRB)], ...
                ['90 if (N>=', num2str(Nmax_SRB), ') then moles = M-', num2str(Mmax_SRB)], ...
                '200 Save moles', ...
                '-end', ...
                'Biomass_ACE', ...
                '-start', ...
                '20 rate = get(3)', ...
                ['30 Y = ', num2str(Y_ACE)], ...
                ['40 b = ', num2str(b_ACE/86400)], ...
                '50 rate = Y*rate-b*M', ...
                '60 moles = -rate * TIME', ...
                ['70 N = (M-moles)*', num2str(MW_ACE*1/m_ACE)], ...
                ['80 if (M-moles)<', num2str(Mmin_ACE), ' then moles = M-', num2str(Mmin_ACE)], ...
                ['90 if (N>=', num2str(Nmax_ACE), ') then moles = M-', num2str(Mmax_ACE)], ...
                '200 Save moles', ...
                '-end', ...
                'Biomass_FRB', ...
                '-start', ...
                '20 rate = get(4)', ...
                ['30 Y = ', num2str(Y_FRB)], ...
                ['40 b = ', num2str(b_FRB/86400)], ...
                '50 rate = Y*rate-b*M', ...
                '60 moles = -rate * TIME', ...
                ['70 N = (M-moles)*', num2str(MW_FRB*1/m_FRB)], ...
                ['80 if (M-moles)<', num2str(Mmin_FRB), ' then moles = M-', num2str(Mmin_FRB)], ...
                ['90 if (N>=', num2str(Nmax_FRB), ') then moles = M-', num2str(Mmax_FRB)], ...
                '200 Save moles', ...
                '-end', ...
                'END', ...
                'SOLUTION 1', ...
                ['-pressure ', num2str(pressure_atm(i))], ...
                ['-temp ', num2str(temp(i)-273.15)], ...
                ['pH ', num2str(pH(i)), ' #charge'], ...
                ['units ', Units], ...
                ['K ', num2str(K(i))], ...
                ['Na ', num2str(Na(i))], ...
                ['Mg ', num2str(Mg(i))], ...
                ['Ca ', num2str(Ca(i))], ...
                ['Cl ', num2str(Cl(i))], ...
                ['Carbonate(4) ', num2str(C4(i))], ...
                ['Sulfate(6) ', num2str(S6(i))], ...
                ['Sulfide(-2) ', num2str(S2(i))], ...
                ['Fe_tri ', num2str(Fe3(i))], ...
                ['Fe_di ', num2str(Fe2(i))], ...
                ['Si ', num2str(Si(i))], ...
                ['Acetate ', num2str(Acetate(i))], ...
                '-water 1', ... % was mass_H2O_Profile(i)/mass_H2O_Profile(i)
                'END', ...
                'Gas_Phase 1', ...
                ['-pressure ', num2str(pressure_atm(i))], ...
                ['-temp ', num2str(temp(i)-273.15)], ...
                '-fixed_volume', ...
                ['-volume ', num2str(Vg(i)./mass_H2O_Profile(i))], ...
                ['H2(g) ', num2str(pH2(i))], ...
                ['redoxCarbonateO2(g) ', num2str(pCO2(i))], ...
                ['redoxCH4(g) ', num2str(pCH4(i))], ...
                ['redoxH2S(g) ', num2str(pH2S(i))], ...
                ['N2(g) ', num2str(pN2(i))], ...
                'Gas_Phase_Modify 1', ...
                '-type 1', ...
                ['-total_p ', num2str(pressure_atm(i))], ...
                ['-volume ', num2str(Vg(i)./mass_H2O_Profile(i))], ...
                '-component H2(g)', ...
                ['-moles ', num2str(mol_H2_Profile(i)./mass_H2O_Profile(i))], ...
                '-component redoxCH4(g)', ...
                ['-moles ', num2str(mol_CH4_Profile(i)./mass_H2O_Profile(i))], ...
                '-component redoxCarbonateO2(g)', ...
                ['-moles ', num2str(mol_CO2_Profile(i)./mass_H2O_Profile(i))], ...
                '-component redoxH2S(g)', ...
                ['-moles ', num2str(mol_H2S_Profile(i)./mass_H2O_Profile(i))], ...
                '-component N2(g)', ...
                ['-moles ', num2str(mol_N2_Profile(i)./mass_H2O_Profile(i))], ...
                'END', ...
                'INCREMENTAL_REACTIONS true', ...
                'KINETICS 1', ...
                'Biomass_SRB', ...
                '-formula H 0', ...
                ['-M0 ', num2str(min(SRB_Biomass(i)./mass_H2O_Profile(i), Mmax_SRB))], ...
                'Biomass_MET', ...
                '-formula H 0', ...
                ['-M0 ', num2str(min(MET_Biomass(i)./mass_H2O_Profile(i), Mmax_MET))], ...
                'Biomass_ACE', ...
                '-formula H 0', ...
                ['-M0 ', num2str(min(ACE_Biomass(i)./mass_H2O_Profile(i), Mmax_ACE))], ...
                'Biomass_FRB', ...
                '-formula H 0', ...
                ['-M0 ', num2str(min(FRB_Biomass(i)./mass_H2O_Profile(i), Mmax_FRB))], ...
                'MET', ...
                ['-M ', num2str(mol_H2_Profile(i)./mass_H2O_Profile(i)), ' moles'], ...
                '-formula HCarbonateO3 -0.25 H2 -1 H+ -0.25 MethaneH4 0.25 H2O 0.75', ...
                'SRB', ...
                ['-M ', num2str(mol_H2_Profile(i)./mass_H2O_Profile(i)), ' moles'], ...
                '-formula SulfateO4 -0.25 H2 -1 H+ -0.25 HSulfide 0.25 H2O 1', ...
                'ACE', ...
                ['-M ', num2str(mol_H2_Profile(i)./mass_H2O_Profile(i)), ' moles'], ...
                '-formula HCarbonateO3 -0.5 H2 -1 H+ -0.25 Acetate 0.25 H2O 1', ...
                'FRB', ...
                ['-M ', num2str(mol_H2_Profile(i)./mass_H2O_Profile(i)), ' moles'], ...
                '-formula  Fe_tri -1 Fe_di +1', ...
                ['-step ', num2str(tot_time), ' in ', num2str(steps), ' steps'], ...
                '-bad_step_max 800', ...
                'END', ...
                'EQUILIBRIUM_PHASES 1', ...
                ['redoxCalcite 0 ',   num2str(Calcite_i(i)/mass_H2O_Profile(i))], ...
                ['redoxDolomite 0 ',  num2str(Dolomite_i(i)/mass_H2O_Profile(i))], ...
                ['redoxAnhydrite 0 ', num2str(Anhydrite_i(i)/mass_H2O_Profile(i))], ...
                ['Quartz 0 ',         num2str(Quartz_i(i)/mass_H2O_Profile(i))], ...
                ['redoxGoethite 0 ',  num2str(Goethite_i(i)/mass_H2O_Profile(i))], ...
                ['redoxPyrite   0 ',  num2str(Pyrite_i(i)/mass_H2O_Profile(i))], ...
                ['Brucite 0  ',       num2str(Brucite_i(i)/mass_H2O_Profile(i))], ...
                ['Portlandite 0  ',   num2str(Portlandite_i(i)/mass_H2O_Profile(i))], ...
                ['redoxGypsum 0  ',   num2str(Gypsum_i(i)/mass_H2O_Profile(i))], ...
                'END', ...
                'USE solution 1', ...
                'USE kinetics 1', ...
                'USE EQUILIBRIUM_PHASES 1', ...
                'USE gas_phase 1', ...
                'USER_PUNCH', ...
                '-headings MET_RATE ACE_RATE SRB_RATE TDS CO3-2 HCO3- TOT_CO2 Dissolved_CO2 Z_Factor act("Ca+2") act("CO3-2") act(CaHCO3+) Ca+2 CaHCO3+', ...
                '-start', ...
                '20 rate1 = get(1)', ...
                '30 Punch rate1', ...
                '40 rate2 = get(3)', ...
                '50 Punch rate2', ...
                '60 rate3 = get(2)', ...
                '70 Punch rate3', ...
                '80 Punch (RHO - TOT("water")/SOLN_VOL)*1e3', ...
                '90 Punch MOL("CarbonateO3-2")', ...
                '91 Punch MOL("HCarbonateO3-")', ...
                '92 Punch GAS("redoxCarbonateO2(g)") + MOL("CarbonateO2")', ...
                '93 Punch TOT("Carbonate(4)") - MOL("CarbonateO3-2") - MOL("HCarbonateO3-") - mol("CaHCarbonateO3+")', ...
                '94 Punch GAS_P*GAS_VM/TK/0.082057366080960', ...
                '95 Punch act("Ca+2")', ...
                '96 Punch act("CarbonateO3-2")', ...
                '97 Punch act("CaHCarbonateO3+")', ...
                '98 Punch mol("Ca+2")', ...
                '99 Punch mol("CaHCarbonateO3+")', ...
                '-end', ...
                'SELECTED_OUTPUT', ...
                '#-high_precision', ...
                '-sim false', ...
                '-step true', ...
                '-soln false', ...
                '-pH true', ...
                '-molalities H2 N2 CarbonateO2 MethaneH4 H2Sulfide',  ...
                '-state false',  ...
                '-water true', ...
                '-time true',  ...
                '-gases H2(g) redoxCarbonateO2(g) redoxCH4(g) redoxH2S(g) N2(g)', ...
                '-distance false', ...
                '-equilibrium_phases redoxCalcite redoxAnhydrite redoxGypsum redoxDolomite redoxGoethite redoxPyrite Brucite Portlandite Quartz', ...
                '-kinetic_reactants Biomass_SRB Biomass_MET Biomass_ACE Biomass_FRB', ...
                '-total Carbonate(4) Sulfate(6) Ca Mg Fe_di Fe_tri K Na Cl Acetate Sulfide(-2) Si', ...
                '-saturation_indices redoxCalcite Brucite Portlandite redoxAnhydrite redoxDolomite Quartz redoxH2S(g)', ...
                'END' ...
                };

            Strings{i,1} = sprintf('%s\n', IPCstringCell{:});
        else
            Strings{i,1} = '';  % no PHREEQC call for this cell
        end
    end
end
